 #加密配置
jasypt:
  encryptor:
    password: talroad
    
spring:
  redis:
    remote: false        #cachecloud 获取
    host: 172.17.240.67
    port: 6379
    #password: 123456
    # timeout: 0
  rabbitmq:
    host: 172.17.240.67
    port: 5672
    username: trkj
    password: 123@abc
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 5
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 500MB

redis:
  cache:
    expiration: 3601

ribbon:
  eager-load:
    enabled: true
    clients: talroad-auth,talroad-base-service
  Httpclient:
    enabled: false
  OkHttp:
    enabled: true
  ReadTimeout: 20000
  ConnectTimeout: 10000

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      feignName:
        connectTimeout: 60000
        readTimeout: 60000
  compression:
    request:
      enabled: true
    response:
      enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

#监控短点配置
management:
  security:
    enabled: false
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false
#fastdfs配置   
fdfs:
  so-timeout: 1501
  connect-timeout: 500
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:          
    - 172.17.240.68:22122
