server:
  port: 8005

spring:
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.200.211:3306/talroad_base?characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: dev
    password: dev


slave:
  datasource:
    names: ds1,ds2,waterFine
    ds1:
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.0.200.211:3306/talroad_base?characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: trkj
      password: t1ch@TR
    ds2:
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.0.200.200:3306/db_enterprise_archives?characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: trkj
      password: t1ch@TR
    waterFine:
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.0.200.44:3306/db_water_fine_control?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false    
      username: liuwenshuang   
      password: azAZ922@lws
      
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: IdasNettyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: cn.cepec.talroad.task.entity
  global-config:
    id-type: 0
    field-strategy: 1
    db-column-underline: true
    refresh-mapper: true
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
