server:
  port: 9002
  
spring:  
  datasource:    
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/talroad_base?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false    
    username: dev  
    password: dev

ignore:
  urls:
    - /authentication/**
    - /**/*.css
    - /info
    - /loggers/**
    - /mobile/token
    - /web/token
