server:
  port: 9004

spring:
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/talroad_base?characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: guye
    password: guye
    
slave:
  datasource:
    names: ds1,ds2
    ds1:
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/talroad_base?characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: guye
      password: guye
    ds2:
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/talroad_base?characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: guye
      password: guye

    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: IdasNettyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: cn.cepec.talroad.event.entity
  global-config:
    id-type: 0
    field-strategy: 1
    db-column-underline: true
    refresh-mapper: true
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
