server:
  port: 9002
  
spring:  
  datasource:    
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/talroad_base?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false    
    username: guye 
    password: guye

ignore:
  urls:
    - /authentication/**
    - /**/*.css
    - /info
    - /loggers/**
    - /mobile/token
    - /web/token
